### ISSUE TITLE
Plex Add-on OSD doesn't close

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.eminence.2#81] opened 2021-09-24 03:20 UTC
Great to see this skin being activated for Kodi 19. One of the issues this skin has had for a long time is that when you use Kodi Plex add-on and play a movie or TV Series the OSD window won't close. Is it possible to request a fix for this? 

Thanks!

**Comment by jurialmunkey** [comment] 2021-09-26 08:56
Which plex addon?

Also what do you mean by OSD window? Do you mean the plex addon one, or the kodi/eminence one? Got a screenshot of the issue?

**Comment by derrgoo** [comment] 2021-09-26 09:06
Sure. Two issues but here is the pics that will explain better. This only happens when using eminence skin. This has happened even when using kodi 18. 

![image](https://user-images.githubusercontent.com/63697905/134801216-6edcbbae-6913-4303-86b1-8ee1ca78215c.jpeg)

![image](https://user-images.githubusercontent.com/63697905/134801222-a1baa61f-9f83-469a-9acd-15f2221ea15d.jpeg)

**Comment by jurialmunkey** [comment] 2021-09-30 02:46
Which plex addon though? I don't use Plex so I need a link to which addon it is.

**Comment by derrgoo** [comment] 2021-09-30 04:00
In the kodi repo under video add ons. 

![image](https://user-images.githubusercontent.com/63697905/135384969-27e5c0d0-c4b3-449c-ac8d-cad58be1a232.jpeg)

**Comment by jurialmunkey** [comment] 2021-09-30 04:22
Here's the problem in the plex addon for seek bar:
https://github.com/plexinc/plex-for-kodi/blob/master/resources/skins/Main/1080i/script-plex-seek_dialog.xml#L12

They are tying visibility of the plex addon seekbar to `Window.IsVisible(seekbar)` -- the problem is that Eminence seekbar is always visible (it just slides off screen rather than closing the window).

That's a poor approach by the Plex addon. They should make their seekbar visible based on Player condition.

**Comment by derrgoo** [comment] 2021-09-30 05:01
I have always wondered why only eminence had the issue. So not much that can be done unless plex changes.

**Comment by jurialmunkey** [comment] 2021-09-30 05:30
@derrgoo - Can you test latest (v4.0.6)?
https://github.com/jurialmunkey/skin.eminence.2/archive/refs/tags/v4.0.6.zip

I think this should fix the seekbar issue. The main reason the eminence seekbar is always visible is because of some animation conditions. I think I've managed to solve all those with other workarounds that will allow for hiding the seekbar. 

It's possible there's some scenario or setting where these new workarounds will cause animation issues but so far all the potentially problematic combinations don't appear to be causing any issues - so if this fixes the plex seekbar issue, then I should be able to leave it in unless it causes some major unfixable bug elsewhere that I've overlooked (it's been so long since working on this skin, I can't remember all the little ins and outs.).

**Comment by derrgoo** [comment] 2021-09-30 05:33
Sounds great. Thanks for the update.

**Comment by jurialmunkey** [comment] 2021-09-30 05:46
^^^ I think that one will fix the missing font issue (Plex addon is using skin specific font definitions, which addons aren't allowed to do. Whoever reviewed the code before allowing it on the repo must've missed that). Anyway, I added some of the definitions that it appears to be using, so hopefully should fix the dialog
https://github.com/jurialmunkey/skin.eminence.2/archive/refs/tags/v4.0.7.zip

> I had one question. Eminence seems to not cache widgets same as artic. Each time you play and go back to widget it has to do a full reload. Artic still shows the loaded widgets. Is that how you designed eminence?

Both skins reload the widgets -- it's just the Eminence specifically hides the widget whilst it's reloading whereas Arctic just keeps showing the old widget until the new one loads.

**Comment by derrgoo** [comment] 2021-09-30 05:57
Okay that makes sense. Hiding until reloading vs showing while reloading. That's why artic feels so much faster with widgets.

**Comment by jurialmunkey** [comment] 2021-09-30 06:01
> Okay that makes sense. Hiding until reloading vs showing while reloading. That's why artic feels so much faster with widgets.

I'll probably change it to follow the Arctic behaviour as I honestly prefer that approach.

The hiding behaviour is really a product of the time Eminence was made where most widgets were library content so loaded quite fast. I think now when it's more likely it'll be a mix of plugin and library content it makes more sense to keep the loading hidden in the background

**Comment by derrgoo** [comment] 2021-09-30 06:06
Yea that's great. It will be so fast then. Which fast now but only widget delays :))) 

Also, hope you consider categories in PVR guide like you did Arctic. Great also for speed of use. 👍

**Comment by derrgoo** [comment] 2021-09-30 06:11
Plex add fix worked perfect. Osd went right away 👍👍

**Closed** 2021-09-30 06:37 UTC
