### ISSUE TITLE
[Request]  Indicators

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.eminence.2#87] opened 2021-10-03 08:32 UTC
Would it be possible to have the watched indicators show on widget posters? I.e. progress, watched ect.  

P.S. it looks like you updated widget to be active seems much faster not having to reload all 👍

![image](https://user-images.githubusercontent.com/63697905/135746053-57acff02-ce4b-44fb-8336-86c2db783e72.png)

**Comment by jurialmunkey** [comment] 2021-10-04 04:08
Duplicate of https://github.com/jurialmunkey/skin.eminence.2/issues/86

**Closed by jurialmunkey** 2021-10-04 04:08 UTC

**Comment by jurialmunkey** [comment] 2021-10-04 04:15
FYI - Already exists. See here: https://github.com/jurialmunkey/skin.eminence.2/issues/86#issuecomment-933127489
